apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-express-deployment
  labels:
    app: example-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-express
  template:
    metadata:
      labels:
        app: example-express
    spec:
      containers:
      - name: example-express
        image: audiazzura23/example-express
        ports:
        - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: example-express-service
  labels:
    app: example-express
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: example-express
